# Generated by Django 3.0.6 on 2020-05-05 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('relative_volume', models.FloatField(blank=True, null=True)),
                ('volume', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('change', models.FloatField(blank=True, null=True)),
                ('float', models.IntegerField(blank=True, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='strategies.Strategy')),
            ],
        ),
    ]
