# Generated by Django 3.0.6 on 2020-05-11 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='public_id',
            field=models.UUIDField(default=uuid.UUID('2274f1e9-ed53-4019-88ef-8af76cabfa12'), editable=False),
        ),
    ]
