# Generated by Django 3.0.6 on 2020-05-11 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
