# Generated by Django 3.0.6 on 2020-05-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20200511_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='five_min_vol',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
