# Generated by Django 3.0.6 on 2020-05-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alert_five_min_vol'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='gap_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='gap_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
